name: farmer_app
description: Farmer Assistant App (Phase 0 scaffold)
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.6
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.39
  collection: ^1.18.0
  audio_session: ^0.1.18
  record: ^5.0.4
  image_picker: ^1.0.7
  camera: ^0.11.0+1
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/i18n/

# Prefer external l10n.yaml for config to avoid synthetic package conflicts


